spring:
  profiles:
    include: oauth2, gcs

  # override datasource during deployment
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

jwt:
  secret: ${JWT_SECRET}
  # 10 minutes
  access-token-time: 600000
  # 1 day
  refresh-token-time: 86400000



server:
  port: 8080

  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: ${KEYSTORE_PASSWORD}