spring:
  profiles:
    include: oauth2, gcs

  # override datasource during deployment
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 16MB

jwt:
  secret: ${JWT_SECRET}
  # 1 minutes
  access-token-time: 60000
  # 1 day
  refresh-token-time: 86400000


server:
  port: ${SERVER_PORT}

  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: ${KEYSTORE_PASSWORD}

  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: never  # Response 에 Stack Trace 를 표시할지 (never | always | on_param)
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부


react:
  uri: ${REACT_URI}

perspective:
  api-key: ${PERSPECTIVE_API_KEY}