spring:
  profiles:
    include: oauth2, gcs, youtube

  # override datasource during deployment
  datasource:
    driver-class-name: ${DATASOURCE_DRIVER_CLASS_NAME}
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: ${MONGODB_DATABASE}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 50MB

jwt:
  secret: ${JWT_SECRET}
  access-token-time: ${ACCESS_TOKEN_TIME}
  refresh-token-time: ${REFRESH_TOKEN_TIME}


server:
  port: ${SERVER_PORT}

  error:
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always       # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: never     # Response 에 Stack Trace 를 표시할지 (never | always | on_param)
    whitelabel.enabled: true      # 에러 발생 시 Spring 기본 에러 페이지 노출 여부

#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-type: PKCS12
#    key-store-password: ${KEYSTORE_PASSWORD}

react:
  uri: ${REACT_URI}

perspective:
  api-key: ${PERSPECTIVE_API_KEY}

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
