name: Java CI with Gradle

on:
  pull_request:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set yml file
      uses: microsoft/variable-substitution@v1
      with:
        files: ./src/main/resources/application.yml, ./src/main/resources/application-oauth2.yml, ./src/main/resources/application-gcs.yml
      env:
        server.port: ${{ secrets.SERVER_PORT }}
        spring.datasource.driver-class-name: ${{ secrets.BUILD_DATASOURCE_DRIVER_CLASS_NAME }}
        spring.datasource.url: ${{ secrets.BUILD_DATASOURCE_URL }}
        spring.datasource.username: ${{ secrets.DATASOURCE_USERNAME }}
        spring.datasource.password: ${{ secrets.DATASOURCE_PASSWORD }}

        spring.security.oauth2.client.registration.google.client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
        spring.security.oauth2.client.registration.google.client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        spring.security.oauth2.client.registration.google.redirect-uri: ${{ secrets.GOOGLE_REDIRECT_URI }}
        spring.security.oauth2.client.registration.facebook.client-id: ${{ secrets.FACEBOOK_CLIENT_ID }}
        spring.security.oauth2.client.registration.facebook.client-secret: ${{ secrets.FACEBOOK_CLIENT_SECRET }}
        spring.security.oauth2.client.registration.facebook.redirect-uri: ${{ secrets.FACEBOOK_REDIRECT_URI }}
        spring.security.oauth2.client.registration.kakao.client-id: ${{ secrets.KAKAO_CLIENT_ID }}
        spring.security.oauth2.client.registration.kakao.client-secret: ${{ secrets.KAKAO_CLIENT_SECRET }}
        spring.security.oauth2.client.registration.kakao.redirect-uri: ${{ secrets.KAKAO_REDIRECT_URI }}

        jwt.secret: ${{ secrets.JWT_SECRET }}
        spring.cloud.gcp.storage.credentials.location: ${{ secrets.GCS_KEY_LOCATION }}
        spring.cloud.gcp.storage.project-id: ${{ secrets.GCS_PROJECT_ID }}
        spring.cloud.gcp.storage.bucket: ${{ secrets.GCS_BUCKET_NAME }}
        spring.cloud.gcp.storage.key-name: ${{ secrets.GCS_KEY_NAME }}
        server.ssl.key-store-password: ${{ secrets.KEYSTORE_PASSWORD }}
        react.uri: ${{ secrets.REACT_URI }}
        perspective.api-key: ${{ secrets.PERSPECTIVE_API_KEY }}

    - name: create-json
      id: create-json
      uses: jsdaniell/create-json@v1.2.2
      with:
        name: ${{ secrets.GCS_KEY_NAME }}
        json: ${{ secrets.GCS_KEY_JSON }}
        dir: ${{ secrets.GCS_KEY_DIR_LOCATION }}

    - name: Keystore Save
      run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > ./src/main/resources/keystore.p12

    - name: Run chmod to make gradlew executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew build