name: Deploy to GCP Instance using SSH

on:
  push:
    branches: ['main']

env:
  PROJECT_ID: 'eighth-alchemy-408113'
  GCE_INSTANCE: 'mylist-server'
  GCE_INSTANCE_ZONE: 'asia-northeast3-a'
  PROJECT_NAME: 'mylist spring server'

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull minskim22/mylist-spring:${GITHUB_SHA::7}
            docker tag minskim22/mylist-spring:${GITHUB_SHA::7} mylist-spring
            docker stop server
            docker run -d --rm --name server -p 8080:8080 mylist-spring